### ISSUE TITLE
ucache-0.1.1 is not pip installable

### ISSUE THREAD

**Issue by mortenlj** [coleifer/ucache#5]
When trying to install ucache with pip, it crashes because `README.md` is not included in the archive:

```
  pip install ucache
Collecting ucache
  Downloading https://files.pythonhosted.org/packages/4b/05/dbf7902a18a6084cc415231bf77683813c93dae6b20219a529429fa57aaa/ucache-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zyq8mc0h/ucache/setup.py", line 5, in <module>
        with open(os.path.join(os.path.dirname(__file__), 'README.md')) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-zyq8mc0h/ucache/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-zyq8mc0h/ucache/
```

**Comment by coleifer** [comment]
Fixed, 0.1.2
